name: Google Search Console Indexing

on:
  workflow_dispatch:

jobs:
  indexing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Submit URLs for Indexing
        uses: yaakaii/indexing-action@v1
        with:
          siteUrl: 'https://symbols.thenepal.io/'
          sitemapPath: 'sitemap.xml'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
