name: Google Indexing Automation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  google-indexing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Google Indexing Script
        uses: itsmesandip/google-indexing-action@v1
        with:
          # Directly target your live Cloudflare Pages sitemap URL
          sitemapUrl: 'https://symbols.thenepal.io/sitemap.xml'
          gcpServiceAccountKey: ${{ secrets.GCP_SA_KEY }}
