name: Generate Automated Sitemaps

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'sitemap.html'
      - 'sitemap.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Sitemap Generator
        run: node generate-sitemap.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.html sitemap.xml
          git diff-index --quiet HEAD || git commit -m "chore: automatically update html and xml sitemaps"
          git push
