name: Generate Automated Sitemaps

on:
  push:
    branches:
      - main # change to your default branch name if different
    paths-ignore:
      - 'sitemap.html'
      - 'sitemap.xml' # Ignore both so the runner doesn't trigger itself

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Run Sitemap Generator
        run: node generate-sitemap.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage both files
          git add sitemap.html sitemap.xml
          
          # Only commit if there are changes to avoid workflow errors
          git diff-index --quiet HEAD || git commit -m "chore: automatically update html and xml sitemaps [skip ci]"
          git push
